option(LALIB_BACKEND "Backend" "Internal")
if (LALIB_BACKEND MATCHES "Internal")
	add_compile_definitions(LALIB_INTERNAL_BACKEND)
elseif (LALIB_BACKEND MATCHES "BLAS")
	find_package(BLAS REQUIRED)
	add_compile_definitions(LALIB_BLAS_BACKEND)
elseif (LALIB_BACKEND MATCHES "LAPACK")
	find_package(LAPACK REQUIRED)
	add_compile_definitions(LALIB_BLAS_BACKEND LALIB_LAPACK_BACKEND)
endif()

option(LALIB_USE_ACCELERATOR "Accelerator" "FALSE")
if (LALIB_USE_ACCELERATOR)
	if (${OpenMP_CXX_VERSION} VERSION_LESS 4.5)
		message(FATAL_ERROR "OpenMP version 4.5 is required to enable hardware acceleration.")
	endif()
	add_compile_definitions(LALIB_USE_ACCELERATOR)
endif()